In [3]:
from agent import run
from prompt import *
import numpy as np
import random
from evaluation import check
import os

In [4]:
times = np.ones((11,20))
corrects = np.ones((11,20))

In [3]:
print(np.mean(times[9]))

1.0


In [10]:
print(times)
print(corrects)

[[  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [ 70.71146202 122.52788281  58.53182721  79.07610297  71.11881804
  112.14946675 104.40019011  61.35067511  81.03254199 101.94808602
   83.26215601  68.54116392  65.60882115 148.33659959  63.47337103
   62.58075404  68.82962918  61.11729598  62.93789411  72.33088207]
 [  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.      

In [15]:
print(times)
print(corrects)

[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.0

In [6]:
print(times)
print(corrects)

[[  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.        ]
 [  1.           1. 

In [6]:
print(times)
print(corrects)

[[ 55.64136481  79.75341797  35.90495491  32.06373715  46.43745804
   89.58281779  36.54903507  50.4603231   88.00701284  76.48819399
   41.479568    37.67618799 129.90359306  71.08981919  38.23343205
   41.98304319  46.87057996  32.77231574  42.21129894  39.58470297]
 [112.04926705  65.66290808  67.86880112  60.36250901  72.86831927
  116.45770788  63.88356304  55.80611515  64.77163577 127.14387107
   74.04833364  63.35602593  71.01945615  66.39510918  76.03851509
   74.12762094  66.53614902  81.2173779   74.24162579 114.81182218]
 [  2.86589408  78.68920183  55.07232785  50.84532785  45.31821275
   64.26644111 119.25553799 101.58783507 109.85268235 136.6387043
   43.33549333  49.85213304  82.06030202 116.0160408   62.18703413
   42.22977591  58.89437127  88.811584    49.62894177  44.24049091]
 [ 46.11640501  70.72796917  50.78469181  56.41279483  54.85904574
   60.431113    45.61746216  60.77494121  80.57592583  54.89484477
   57.31621981  63.80281615  53.25617218 104.26904011  53.99

In [6]:
test_files = []

In [7]:
for i in range(1,2):
    if i == 8:
        continue
    used_datas = random.sample(range(1,97), 20)
    print(used_datas)
    test_files.append(used_datas)
    count = 0
    for j in used_datas:
        print(j)
        s = str(j)
        file1 = "data/" + s + ".txt"
        file2 = "data/" + s + "_original.npy"
        file3 = "result/" + str(i+1) + "_" + s + ".npy"
        file4 = "result/" + str(i+1) + "_" + s + ".py"
        log_name = "log/" + str(i+1) + "_" + s + ".txt"
        print(file1, file2, file3, file4,log_name)
        input = generate_input(file1,file2,file3,file4,task_requirements(i+1),data_formats(i+1))
        print(input)
        times[i][count] = run(input,log_name=log_name)
        corrects[i][count] = check(file2, file3, 0.01, i + 1)
        count = count + 1
    #     break
    # break
    print("The average used time is: ")
    print(np.mean(times[i]))
    print("correct number is")
    print(np.sum(corrects[i] == 0))
    directory = "data"
    for file in os.listdir(directory):
        if file.endswith('.npy'):
            file_path = os.path.join(directory, file)
            os.remove(file_path)
np.save("used_time.npy", times)
np.save("corrects.npy", corrects)
    

[57, 76, 25, 61, 45, 22, 72, 24, 66, 15, 65, 63, 85, 28, 12, 55, 18, 80, 95, 88]
57
data/57.txt data/57_original.npy result/2_57.npy result/2_57.py log/2_57.txt
(1)使用parse_eeg_data工具，解析同目录下的data/57.txt；(2)编写并且运行python代码，对同目录下的data/57_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_57.npy, (3)将代码保存到result/2_57.py


Python REPL can execute arbitrary code. Use with caution.


task (1)使用parse_eeg_data工具，解析同目录下的data/57.txt；(2)编写并且运行python代码，对同目录下的data/57_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_57.npy, (3)将代码保存到result/2_57.py is over!
成功读取数据。数组形状为: (7, 104325)
开始计算频段能量，共39个窗口...
[[[9.54386319e+02 1.69134262e+02 1.18667534e+02 2.56340597e+02]
  [2.48407939e+03 2.59236540e+02 9.89097628e+01 1.62150611e+02]
  [4.62839676e+03 4.69229492e+02 9.28879287e+01 2.01526496e+02]
  ...
  [3.44248829e+03 3.34155889e+02 1.47514483e+02 2.82445267e+02]
  [3.91233268e+03 8.84779056e+02 3.89728146e+02 5.09699186e+02]
  [2.23307012e+03 2.66911097e+02 2.10216613e+02 3.10101835e+02]]

 [[6.55808920e+02 1.99664556e+02 8.25906826e+01 2.18152681e+02]
  [2.06576251e+03 2.62435515e+02 7.52640782e+01 1.62449122e+02]
  [4.91789199e+03 4.27312765e+02 8.78011984e+01 1.92362807e+02]
  ...
  [3.69652991e+03 4.53431441e+02 1.14293839e+02 2.53157053e+02]
  [3.31949980e+03 7.55307740e+02 3.85526252e+02 4.56594422e+02]


Stopping agent prematurely due to triggering stop condition


task (1)使用parse_eeg_data工具，解析同目录下的data/65.txt；(2)编写并且运行python代码，对同目录下的data/65_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_65.npy, (3)将代码保存到result/2_65.py is over!
63
data/63.txt data/63_original.npy result/2_63.npy result/2_63.py log/2_63.txt
(1)使用parse_eeg_data工具，解析同目录下的data/63.txt；(2)编写并且运行python代码，对同目录下的data/63_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_63.npy, (3)将代码保存到result/2_63.py
task (1)使用parse_eeg_data工具，解析同目录下的data/63.txt；(2)编写并且运行python代码，对同目录下的data/63_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_63.npy, (3)将代码保存到result/2_63.py is over!
成功读取数据。数组形状为: (7, 107950)
开始计算频段能量，共41个窗口...
[[[ 4310.49967183   562.42992536   295.71086259   634.72979387]
  [ 8725.18964715   412.21228495   240.73544666   400.20794864]
  [12603.05807667   746.76478554   287.57699293   

Stopping agent prematurely due to triggering stop condition


task (1)使用parse_eeg_data工具，解析同目录下的data/28.txt；(2)编写并且运行python代码，对同目录下的data/28_original.npy,将数据分30s为一段，使用滑窗模式，滑窗长度10s，计算每个通道的Delta、Theta、Alpha、Beta频段能量，打印结果, 将数值以(x,7,4[x取决于具体数据]的格式存到同目录下的result/2_28.npy, (3)将代码保存到result/2_28.py is over!
成功读取数据。数组形状为: (7, 134110)
开始计算频段能量，共51个窗口...
[[[ 1143.6816263    190.1310545    106.9124825    245.61757919]
  [ 3741.07136996   208.90050001    82.2215859    170.89279645]
  [  457.73171513    94.8751435     89.89776885   154.46134805]
  ...
  [  552.94060358   105.93079544    90.36354568   175.21934936]
  [  725.91742847    94.07345751    57.7590892    101.74486136]
  [  748.79581534   226.76531635   144.71867426   277.9132362 ]]

 [[ 1270.95591029   129.7879616    102.64613157   208.97225101]
  [ 3252.34080734   158.36193144    78.9160125    145.47318167]
  [  814.75163123    88.87270012    77.14833139   168.30370887]
  ...
  [ 1836.78054039    73.71333395    76.24019269   217.35273295]
  [ 1452.2834436     80.39139764    57.6214093    105.84835255]


[43, 13, 8, 41, 53, 64, 39, 30, 66, 12, 46, 93, 2, 32, 51, 65, 73, 42, 44, 18]
[35, 21, 72, 66, 34, 8, 54, 63, 78, 82, 52, 96, 5, 79, 26, 17, 61, 39, 20, 15]
[59, 14, 85, 54, 92, 15, 86, 48, 71, 60, 34, 64, 49, 32, 6, 53, 25, 23, 36, 50]
[55, 69, 16, 12, 82, 21, 44, 73, 35, 75, 13, 42, 79, 78, 38, 48, 53, 70, 34, 24]
[55, 91, 75, 24, 7, 73, 17, 41, 40, 90, 52, 4, 39, 8, 45, 37, 35, 49, 36, 33]

[48, 41, 63, 37, 39, 49, 84, 3, 44, 38, 64, 12, 54, 20, 24, 18, 55, 61, 32, 91]

[64, 76, 42, 8, 71, 29, 82, 78, 16, 39, 30, 9, 59, 38, 54, 6, 21, 17, 5, 69]

[47, 45, 57, 42, 76, 65, 28, 16, 5, 54, 69, 91, 8, 17, 3, 20, 60, 63, 64, 26]

7: [26, 92, 54, 41, 93, 59, 28, 35, 42, 34, 65, 61, 90, 29, 49, 23, 91, 64, 77, 72]
8: [17, 76, 50, 30, 69, 86, 35, 67, 8, 44, 46, 39, 41, 5, 75, 37, 9, 45, 73, 81]
10: [29, 91, 43, 8, 76, 90, 58, 1, 55, 20, 32, 53, 25, 38, 70, 49, 64, 48, 83, 46]
11: 


[[ 55.64136481  79.75341797  35.90495491  32.06373715  46.43745804
   89.58281779  36.54903507  50.4603231   88.00701284  76.48819399
   41.479568    37.67618799 129.90359306  71.08981919  38.23343205
   41.98304319  46.87057996  32.77231574  42.21129894  39.58470297]
 [112.04926705  65.66290808  67.86880112  60.36250901  72.86831927
  116.45770788  63.88356304  55.80611515  64.77163577 127.14387107
   74.04833364  63.35602593  71.01945615  66.39510918  76.03851509
   74.12762094  66.53614902  81.2173779   74.24162579 114.81182218]
 [  2.86589408  78.68920183  55.07232785  50.84532785  45.31821275
   64.26644111 119.25553799 101.58783507 109.85268235 136.6387043
   43.33549333  49.85213304  82.06030202 116.0160408   62.18703413
   42.22977591  58.89437127  88.811584    49.62894177  44.24049091]
 [ 46.11640501  70.72796917  50.78469181  56.41279483  54.85904574
   60.431113    45.61746216  60.77494121  80.57592583  54.89484477
   57.31621981  63.80281615  53.25617218 104.26904011  53.99500513
   43.59327602  55.39144826  55.79329085  54.65386915  45.54296899]
 [104.91110182  53.494766     0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]]
[[ 0.  0.  0.  0.  0.  0. -1.  0.  0. -1. -1.  0.  0. -1. -1.  0.  0.  0.
   0.  0.]
 [-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
  -1. -1.]
 [-1.  0.  0.  0.  0.  0. -1. -1.  0. -1.  0.  0.  0. -1.  0.  0.  0.  0.
   0.  0.]
 [ 1. -1.  0.  0.  0.  1.  1.  0. -1.  0.  0. -1.  0. -1.  1.  1. -1.  0.
   1.  1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]]

In [17]:
# from reference_code import sol_6
from agent import parse_eeg_data
import numpy as np
from evaluation import check
s = "86"
parse_eeg_data("data/"+s+".txt")
x = np.load("result/8_"+s+".npy")
# print(x[0])
print(x)
print(check("data/"+s+"_original.npy", "result/8_"+s+".npy",0.01,8))

[[ 101864.27215067]
 [ 103809.47332302]
 [  51771.33821129]
 [1133946.57937714]
 [ 163050.10639909]
 [  23653.56292007]
 [ 112012.12765076]]
solve.npy
SSVEP振幅结果已保存到 solve.npy
0


In [13]:
import numpy as np
from scipy.signal import welch

# 定义频段范围
BANDS = {
    'Delta': (0.5, 4),
    'Theta': (4, 8),
    'Alpha': (8, 13),
    'Beta': (13, 30)
}

def compute_band_energies(window_data, fs=250):
    """
    计算单个窗口内各通道的频段能量
    :param window_data: 窗口数据 (7, window_samples)
    :param fs: 采样频率
    :return: 字典形式的频段能量结果
    """
    n_channels, n_samples = window_data.shape
    results = {band: np.zeros(n_channels) for band in BANDS}
    
    for ch_idx in range(n_channels):
        # 计算功率谱密度 (PSD)
        freqs, psd = welch(
            window_data[ch_idx], 
            fs=fs,
            nperseg=min(500, n_samples),  # 适当的分段长度
            noverlap=min(250, n_samples//2),  # 50%重叠
            scaling='density'
        )
        
        for band, (low, high) in BANDS.items():
            # 选择频段内的频率
            band_mask = (freqs >= low) & (freqs <= high)
            # 使用梯形法计算频段能量（积分）
            results[band][ch_idx] = np.trapz(psd[band_mask], freqs[band_mask])
    
    return results

def process_eeg_signal(eeg_data, fs=250, segment_length=30, window_length=10):
    """
    处理EEG信号：分段+滑窗计算频段能量
    :param eeg_data: 输入EEG数据 (7, x)
    :param fs: 采样频率
    :param segment_length: 分段长度（秒）
    :param window_length: 窗口长度（秒）
    """
    n_channels, total_samples = eeg_data.shape
    total_duration = total_samples / fs
    
    # 计算样本点数
    segment_samples = int(segment_length * fs)
    window_samples = int(window_length * fs)
    
    # 检查数据长度是否足够
    if total_samples < segment_samples:
        print(f"数据不足一个完整段！需要{segment_length}s，实际{total_duration:.1f}s")
        return
    
    # 计算段数和每段中的窗口数
    n_segments = total_samples // segment_samples
    windows_per_segment = segment_samples // window_samples
    
    print(f"信号总时长: {total_duration:.1f}s")
    print(f"分段数: {n_segments} | 每段窗口数: {windows_per_segment}")
    print("=" * 60)
    
    # 处理每个段
    for seg_idx in range(n_segments):
        seg_start = seg_idx * segment_samples
        seg_end = seg_start + segment_samples
        segment = eeg_data[:, seg_start:seg_end]
        
        print(f"\n段 {seg_idx+1}/{n_segments} ({seg_idx*segment_length}-{(seg_idx+1)*segment_length}s):")
        print("-" * 50)
        
        # 处理段内的每个窗口
        for win_idx in range(windows_per_segment):
            win_start = win_idx * window_samples
            win_end = win_start + window_samples
            window = segment[:, win_start:win_end]
            
            # 计算频段能量
            energies = compute_band_energies(window, fs)
            
            # 打印结果
            print(f"窗口 {win_idx+1} (t={seg_idx*segment_length + win_idx*window_length}-"
                  f"{seg_idx*segment_length + (win_idx+1)*window_length}s):")
            
            for ch in range(n_channels):
                print(f"  通道 {ch+1}: ", end="")
                for band in BANDS:
                    print(f"{band}: {energies[band][ch]:.4e}", end=" | ")
                print()
            print()

# # 示例用法
# if __name__ == "__main__":
#     # 创建模拟数据：7个通道，300秒数据（75000个样本）
fs = 250
data = np.load("data/"+s+"_original.npy")
    # 处理信号
process_eeg_signal(
        data, 
        fs=fs,
        segment_length=30,
        window_length=10
)

信号总时长: 525.5s
分段数: 17 | 每段窗口数: 3

段 1/17 (0-30s):
--------------------------------------------------
窗口 1 (t=0-10s):
  通道 1: Delta: 9.7662e+00 | Theta: 3.1361e+00 | Alpha: 2.2810e+00 | Beta: 4.3075e+00 | 
  通道 2: Delta: 6.2580e+00 | Theta: 3.6789e+00 | Alpha: 1.8141e+00 | Beta: 3.4820e+00 | 
  通道 3: Delta: 9.6300e+00 | Theta: 2.5271e+00 | Alpha: 1.7309e+00 | Beta: 3.7678e+00 | 
  通道 4: Delta: 2.3575e+01 | Theta: 6.3322e+00 | Alpha: 6.5455e+00 | Beta: 8.3133e+00 | 
  通道 5: Delta: 1.5011e+01 | Theta: 4.0828e+00 | Alpha: 2.0181e+00 | Beta: 4.6226e+00 | 
  通道 6: Delta: 1.1915e+01 | Theta: 1.8015e+00 | Alpha: 1.7543e+00 | Beta: 3.1187e+00 | 
  通道 7: Delta: 9.3154e+00 | Theta: 3.9446e+00 | Alpha: 4.3177e+00 | Beta: 6.3126e+00 | 

窗口 2 (t=10-20s):
  通道 1: Delta: 1.5967e+01 | Theta: 3.0173e+00 | Alpha: 1.7963e+00 | Beta: 5.0751e+00 | 
  通道 2: Delta: 1.7062e+01 | Theta: 2.6986e+00 | Alpha: 1.4255e+00 | Beta: 3.7070e+00 | 
  通道 3: Delta: 2.2437e+01 | Theta: 2.9056e+00 | Alpha: 1.6498e+00 | Beta:

/var/folders/0x/vwp7kdd14n73yn71fv6wbyhw0000gn/T/ipykernel_20306/3971639807.py:36: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  results[band][ch_idx] = np.trapz(psd[band_mask], freqs[band_mask])
